# Generated by Django 6.0.7 on 2026-08-19 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание')),
                ('place', models.CharField(blank=True, max_length=256, verbose_name='Место проведения')),
                ('precision', models.CharField(choices=[('year', 'Год'), ('month', 'Месяц'), ('day', 'День'), ('time', 'Время')], default='time', max_length=10, verbose_name='Точность')),
                ('start_datetime', models.CharField(help_text='Дата начала мероприятия, например, 11.05.2006', max_length=40, verbose_name='Дата начала')),
                ('end_datetime', models.CharField(blank=True, help_text='Дата конца мероприятия, например, 11.05.2006', max_length=40, null=True, verbose_name='Дата конца')),
                ('registration_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на регистрацию')),
            ],
            options={
                'verbose_name': 'Запланированное мероприятие',
                'verbose_name_plural': 'Запланированные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='PastEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание')),
                ('place', models.CharField(blank=True, max_length=256, verbose_name='Место проведения')),
                ('precision', models.CharField(choices=[('year', 'Год'), ('month', 'Месяц'), ('day', 'День'), ('time', 'Время')], default='time', max_length=10, verbose_name='Точность')),
                ('start_datetime', models.CharField(help_text='Дата начала мероприятия, например, 11.05.2006', max_length=40, verbose_name='Дата начала')),
                ('end_datetime', models.CharField(blank=True, help_text='Дата конца мероприятия, например, 11.05.2006', max_length=40, null=True, verbose_name='Дата конца')),
                ('album_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на альбом')),
            ],
            options={
                'verbose_name': 'Прошедшее мероприятие',
                'verbose_name_plural': 'Прошедшие мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Изображение')),
                ('future_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.futureevents')),
                ('past_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.pastevents')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('future_event__isnull', True), ('past_event__isnull', False)), models.Q(('future_event__isnull', False), ('past_event__isnull', True)), _connector='OR'), name='only_one_event_link')],
            },
        ),
    ]
