# Generated by Django 6.0.7 on 2026-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
        migrations.AddField(
            model_name='pastevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
    ]
