# Generated by Django 6.0.7 on 2026-09-27 16:03

from django.db import migrations, models


def backfill_start_date(apps, schema_editor):
    from dateutil.parser import parse

    for model_name in ("futureevents", "pastevents"):
        model = apps.get_model("events", model_name)
        for event in model.objects.all():
            parsed = None
            try:
                if event.start_datetime:
                    parsed = parse(event.start_datetime, dayfirst=True, fuzzy=True)
            except (ValueError, TypeError, OverflowError):
                parsed = None
            if parsed is not None and parsed.tzinfo is not None:
                parsed = parsed.replace(tzinfo=None)
            model.objects.filter(pk=event.pk).update(start_date=parsed)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_futureevents_extended_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureevents',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Заполняется автоматически из «Дата начала» при сохранении, используется для сортировки на уровне БД', null=True, verbose_name='Дата начала (нормализованная)'),
        ),
        migrations.AddField(
            model_name='pastevents',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Заполняется автоматически из «Дата начала» при сохранении, используется для сортировки на уровне БД', null=True, verbose_name='Дата начала (нормализованная)'),
        ),
        migrations.AlterField(
            model_name='futureevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела             «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела             «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
        migrations.RunPython(backfill_start_date, migrations.RunPython.noop),
    ]
