# Generated by Django 6.0.7 on 2026-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_futureevents_extended_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела             «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='extended_description',
            field=models.TextField(blank=True, help_text='Развёрнутое описание для подраздела             «О мероприятии» на странице мероприятия', verbose_name='Развёрнутое описание'),
        ),
    ]
