# Generated by Django 6.0.7 on 2026-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
