# Generated by Django 6.0.7 on 2026-09-27 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partners_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'))], verbose_name='Изображение'),
        ),
    ]
