# Generated by Django 5.2.4 on 2025-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Изображение'),
        ),
    ]
