# Generated by Django 5.2.4 on 2025-10-27 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureevents',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет в формате HEX, например FFFFFF', max_length=6, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX, например FFFFFF', regex='^(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='pastevents',
            name='color',
            field=models.CharField(blank=True, help_text='Цвет в формате HEX, например FFFFFF', max_length=6, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX, например FFFFFF', regex='^(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет'),
        ),
    ]
