# Generated by Django 5.2.4 on 2025-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_futureevents_color_pastevents_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureevents',
            name='place',
            field=models.TextField(blank=True, verbose_name='Место провидения'),
        ),
        migrations.AddField(
            model_name='pastevents',
            name='place',
            field=models.TextField(blank=True, verbose_name='Место провидения'),
        ),
        migrations.AlterField(
            model_name='futureevents',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
