# Generated by Django 5.2.4 on 2025-07-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='future_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_images', to='events.futureevents'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='past_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_images', to='events.pastevents'),
        ),
        migrations.AlterField(
            model_name='futureevents',
            name='end_datetime',
            field=models.CharField(blank=True, help_text='Дата конца мероприятия, например, 11.05.2006', max_length=40, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='futureevents',
            name='start_datetime',
            field=models.CharField(help_text='Дата начала мероприятия, например, 11.05.2006', max_length=40, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='end_datetime',
            field=models.CharField(blank=True, help_text='Дата конца мероприятия, например, 11.05.2006', max_length=40, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='start_datetime',
            field=models.CharField(help_text='Дата начала мероприятия, например, 11.05.2006', max_length=40, verbose_name='Дата начала'),
        ),
    ]
