# Generated by Django 5.2.4 on 2025-11-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_futureevents_place_pastevents_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='future_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.futureevents'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='past_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.pastevents'),
        ),
        migrations.AlterField(
            model_name='futureevents',
            name='place',
            field=models.TextField(blank=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='place',
            field=models.TextField(blank=True, verbose_name='Место проведения'),
        ),
        migrations.AddConstraint(
            model_name='eventimages',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('future_event__isnull', True), ('past_event__isnull', False)), models.Q(('future_event__isnull', False), ('past_event__isnull', True)), _connector='OR'), name='only_one_event_link'),
        ),
    ]
