services:
  backend:
    container_name: stud-iu-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production_build
      args:
        DJANGO_ENV: production
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             exec gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --access-logfile - --error-logfile -"
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DJANGO_DATABASE_HOST: $DJANGO_DATABASE_HOST
      DJANGO_DATABASE_PORT: $DJANGO_DATABASE_PORT
    ports:
      - "${EXTERNAL_HTTP_PORT:-8000}:8000"
    volumes:
      - ${DJANGO_MEDIA_VOLUME:-stud_media}:/app/media
      - ${DJANGO_STATIC_VOLUME:-stud_static}:/app/static

volumes:
  stud_media:
  stud_static: