[project]
name = "stud-iu-back"
version = "0.1.0"
authors = [
    { name = "Елькин Кирилл", email = "kirillv.2016@mail.ru" }
]
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "django-axes>=8.3.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "django-modern-rest[msgspec]>=0.12.1",
    "gunicorn>=26.1.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "python-dateutil>=2.9.0.post0",
    "whitenoise[brotli]>=6.12.0",
]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]

[tool.ruff]
extend-exclude = ["**/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I",]
ignore = ["F401"]
