[project]
name = "stud-iu-back"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "django-modern-rest[msgspec]>=0.12.1",
]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]
