# Generated by Django 5.2.4 on 2025-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, help_text='Обложка', null=True, upload_to='images/news/', verbose_name='Обложка'),
        ),
    ]
