# Generated by Django 5.2.4 on 2025-07-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название организации партнера', verbose_name='Название')),
                ('url', models.URLField(blank=True, help_text='Ссылка на организацию партнера', verbose_name='Ссылка')),
                ('image', models.ImageField(help_text='Изображение логотипа партнёра', upload_to='images/partners/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
