# Generated by Django 6.0.7 on 2026-08-06 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Фамилия, имя и отчество члена руководящего состава, например, Николай Эрнестович Бауман', verbose_name='ФИО')),
                ('link', models.TextField()),
                ('position', models.TextField(verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/board_member/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Член руководящего состава',
                'verbose_name_plural': 'Члены руководящего состава',
            },
        ),
    ]
