# Generated by Django 6.0.7 on 2026-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='name',
            field=models.CharField(help_text='Фамилия, имя и отчество члена руководящего состава, например, Николай Эрнестович Бауман', max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='position',
            field=models.CharField(max_length=256, verbose_name='Должность'),
        ),
    ]
