# Generated by Django 6.0.7 on 2026-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_members', '0002_alter_boardmember_link_alter_boardmember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='name',
            field=models.CharField(help_text='Фамилия, имя и отчество члена руководящего состава,             например, Николай Эрнестович Бауман', max_length=256, verbose_name='ФИО'),
        ),
    ]
