# Generated by Django 5.2.4 on 2025-07-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Фамилия, имя и отчество члена руководящего состава, например, Николай Эрнестович Бауман', verbose_name='ФИО')),
                ('telegram_link', models.TextField(help_text='Ссылка на профиль в Telegram', verbose_name='Телеграм')),
                ('position', models.TextField(verbose_name='Должность')),
                ('start_date', models.DateField(help_text='Дата вступления в должность, например, 11.05.2006', verbose_name='Дата вступления в должность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/board_member/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Член руководящего состава',
                'verbose_name_plural': 'Члены руководящего состава',
            },
        ),
    ]
