# Generated by Django 6.0.7 on 2026-08-19 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=256)),
                ('group', models.CharField(max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('vk_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в vk')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Профиль на GitHub')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
