# Generated by Django 6.0.7 on 2026-08-29 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('group', models.CharField(max_length=64, verbose_name='Учебная группа')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('telegram_url', models.URLField(verbose_name='Ссылка на Telegram')),
                ('vk_url', models.URLField(verbose_name='Ссылка на VK')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Профиль на GitHub')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Портфолио по работе с визуальным контентом')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Выбранные виды деятельности')),
                ('tech_tasks', models.JSONField(blank=True, default=list, verbose_name='Технические задачи')),
                ('visual_content_types', models.JSONField(blank=True, default=list, verbose_name='Виды визуального контента')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
