# Generated by Django 6.0.7 on 2026-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='vk_url',
        ),
        migrations.AlterField(
            model_name='application',
            name='telegram_url',
            field=models.CharField(max_length=32, verbose_name='Никнейм в Telegram'),
        ),
    ]
