# Generated by Django 6.0.7 on 2026-09-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_vk_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='telegram_url',
            new_name='telegram',
        ),
    ]
